<?xml version="1.0" encoding="UTF-8"?><testrun name="TestDB4OSerialiser" project="PADL Serialiser DB4O Tests" tests="11" started="11" failures="0" errors="11" ignored="0">
  <testsuite name="TestSuite with 11 tests [example: padl.serialiser.test.TestDB4OSerialiserSanity]" time="4.302">
    <testsuite name="padl.serialiser.test.TestDB4OSerialiserSanity" time="1.295">
      <testcase name="testEntities" classname="padl.serialiser.test.TestDB4OSerialiserSanity" time="0.797">
        <error>com.db4o.ext.DatabaseClosedException&#13;
	at com.db4o.internal.ObjectContainerBase.checkClosed(ObjectContainerBase.java:308)&#13;
	at com.db4o.internal.ObjectContainerBase.checkTransaction(ObjectContainerBase.java:336)&#13;
	at com.db4o.internal.ObjectContainerBase.asTopLevelCall(ObjectContainerBase.java:420)&#13;
	at com.db4o.internal.ObjectContainerBase.commit(ObjectContainerBase.java:397)&#13;
	at com.db4o.internal.ExternalObjectContainer.commit(ExternalObjectContainer.java:41)&#13;
	at padl.serialiser.DB4OSerialiser.serialise(DB4OSerialiser.java:131)&#13;
	at padl.serialiser.DB4OSerialiser.serialiseWithAutomaticNaming(DB4OSerialiser.java:114)&#13;
	at padl.serialiser.test.TestDB4OSerialiserSanity.setUp(TestDB4OSerialiserSanity.java:34)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:140)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:130)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
&#13;
</error>
      </testcase>
      <testcase name="testNames" classname="padl.serialiser.test.TestDB4OSerialiserSanity" time="0.132">
        <error>com.db4o.ext.DatabaseClosedException&#13;
	at com.db4o.internal.ObjectContainerBase.checkClosed(ObjectContainerBase.java:308)&#13;
	at com.db4o.internal.ObjectContainerBase.checkTransaction(ObjectContainerBase.java:336)&#13;
	at com.db4o.internal.ObjectContainerBase.asTopLevelCall(ObjectContainerBase.java:420)&#13;
	at com.db4o.internal.ObjectContainerBase.commit(ObjectContainerBase.java:397)&#13;
	at com.db4o.internal.ExternalObjectContainer.commit(ExternalObjectContainer.java:41)&#13;
	at padl.serialiser.DB4OSerialiser.serialise(DB4OSerialiser.java:131)&#13;
	at padl.serialiser.DB4OSerialiser.serialiseWithAutomaticNaming(DB4OSerialiser.java:114)&#13;
	at padl.serialiser.test.TestDB4OSerialiserSanity.setUp(TestDB4OSerialiserSanity.java:34)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:140)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:130)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
&#13;
</error>
      </testcase>
      <testcase name="testElements" classname="padl.serialiser.test.TestDB4OSerialiserSanity" time="0.113">
        <error>com.db4o.ext.DatabaseClosedException&#13;
	at com.db4o.internal.ObjectContainerBase.checkClosed(ObjectContainerBase.java:308)&#13;
	at com.db4o.internal.ObjectContainerBase.checkTransaction(ObjectContainerBase.java:336)&#13;
	at com.db4o.internal.ObjectContainerBase.asTopLevelCall(ObjectContainerBase.java:420)&#13;
	at com.db4o.internal.ObjectContainerBase.commit(ObjectContainerBase.java:397)&#13;
	at com.db4o.internal.ExternalObjectContainer.commit(ExternalObjectContainer.java:41)&#13;
	at padl.serialiser.DB4OSerialiser.serialise(DB4OSerialiser.java:131)&#13;
	at padl.serialiser.DB4OSerialiser.serialiseWithAutomaticNaming(DB4OSerialiser.java:114)&#13;
	at padl.serialiser.test.TestDB4OSerialiserSanity.setUp(TestDB4OSerialiserSanity.java:34)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:140)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:130)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
&#13;
</error>
      </testcase>
      <testcase name="testModels" classname="padl.serialiser.test.TestDB4OSerialiserSanity" time="0.103">
        <error>com.db4o.ext.DatabaseClosedException&#13;
	at com.db4o.internal.ObjectContainerBase.checkClosed(ObjectContainerBase.java:308)&#13;
	at com.db4o.internal.ObjectContainerBase.checkTransaction(ObjectContainerBase.java:336)&#13;
	at com.db4o.internal.ObjectContainerBase.asTopLevelCall(ObjectContainerBase.java:420)&#13;
	at com.db4o.internal.ObjectContainerBase.commit(ObjectContainerBase.java:397)&#13;
	at com.db4o.internal.ExternalObjectContainer.commit(ExternalObjectContainer.java:41)&#13;
	at padl.serialiser.DB4OSerialiser.serialise(DB4OSerialiser.java:131)&#13;
	at padl.serialiser.DB4OSerialiser.serialiseWithAutomaticNaming(DB4OSerialiser.java:114)&#13;
	at padl.serialiser.test.TestDB4OSerialiserSanity.setUp(TestDB4OSerialiserSanity.java:34)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:140)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:130)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
&#13;
</error>
      </testcase>
      <testcase name="testInheritance" classname="padl.serialiser.test.TestDB4OSerialiserSanity" time="0.148">
        <error>com.db4o.ext.DatabaseClosedException&#13;
	at com.db4o.internal.ObjectContainerBase.checkClosed(ObjectContainerBase.java:308)&#13;
	at com.db4o.internal.ObjectContainerBase.checkTransaction(ObjectContainerBase.java:336)&#13;
	at com.db4o.internal.ObjectContainerBase.asTopLevelCall(ObjectContainerBase.java:420)&#13;
	at com.db4o.internal.ObjectContainerBase.commit(ObjectContainerBase.java:397)&#13;
	at com.db4o.internal.ExternalObjectContainer.commit(ExternalObjectContainer.java:41)&#13;
	at padl.serialiser.DB4OSerialiser.serialise(DB4OSerialiser.java:131)&#13;
	at padl.serialiser.DB4OSerialiser.serialiseWithAutomaticNaming(DB4OSerialiser.java:114)&#13;
	at padl.serialiser.test.TestDB4OSerialiserSanity.setUp(TestDB4OSerialiserSanity.java:34)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:140)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:130)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
&#13;
</error>
      </testcase>
    </testsuite>
    <testsuite name="padl.serialiser.test.TestDB4OSerialiserJHotDraw51" time="2.964">
      <testcase name="testEntities" classname="padl.serialiser.test.TestDB4OSerialiserJHotDraw51" time="2.955">
        <error>com.db4o.ext.DatabaseClosedException&#13;
	at com.db4o.internal.ObjectContainerBase.checkClosed(ObjectContainerBase.java:308)&#13;
	at com.db4o.internal.ObjectContainerBase.checkTransaction(ObjectContainerBase.java:336)&#13;
	at com.db4o.internal.ObjectContainerBase.asTopLevelCall(ObjectContainerBase.java:420)&#13;
	at com.db4o.internal.ObjectContainerBase.commit(ObjectContainerBase.java:397)&#13;
	at com.db4o.internal.ExternalObjectContainer.commit(ExternalObjectContainer.java:41)&#13;
	at padl.serialiser.DB4OSerialiser.serialise(DB4OSerialiser.java:131)&#13;
	at padl.serialiser.DB4OSerialiser.serialiseWithAutomaticNaming(DB4OSerialiser.java:114)&#13;
	at padl.serialiser.test.TestDB4OSerialiserJHotDraw51.setUp(TestDB4OSerialiserJHotDraw51.java:52)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:140)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:130)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
&#13;
</error>
      </testcase>
      <testcase name="testNames" classname="padl.serialiser.test.TestDB4OSerialiserJHotDraw51" time="0.001">
        <error>java.lang.NullPointerException: Cannot invoke "padl.kernel.IAbstractLevelModel.getDisplayName()" because "padl.serialiser.test.TestDB4OSerialiserJHotDraw51.SerialisedAbstractLevelModel" is null&#13;
	at padl.serialiser.test.TestDB4OSerialiserJHotDraw51.testNames(TestDB4OSerialiserJHotDraw51.java:68)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)&#13;
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:177)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:142)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:130)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
&#13;
</error>
      </testcase>
      <testcase name="testElements" classname="padl.serialiser.test.TestDB4OSerialiserJHotDraw51" time="0.004">
        <error>java.lang.NullPointerException: Cannot invoke "padl.kernel.IAbstractModel.getNumberOfTopLevelEntities()" because "anAbstractModel" is null&#13;
	at padl.util.Util.getArrayOfTopLevelEntities(Util.java:258)&#13;
	at padl.serialiser.test.TestDB4OSerialiserJHotDraw51.testElements(TestDB4OSerialiserJHotDraw51.java:76)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)&#13;
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:177)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:142)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:130)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
&#13;
</error>
      </testcase>
      <testcase name="testInheritance" classname="padl.serialiser.test.TestDB4OSerialiserJHotDraw51" time="0.002">
        <error>java.lang.NullPointerException: Cannot invoke "padl.kernel.IAbstractModel.getNumberOfTopLevelEntities()" because "anAbstractModel" is null&#13;
	at padl.util.Util.getArrayOfTopLevelEntities(Util.java:258)&#13;
	at padl.serialiser.test.TestDB4OSerialiserJHotDraw51.testInheritance(TestDB4OSerialiserJHotDraw51.java:149)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)&#13;
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:177)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:142)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:130)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
&#13;
</error>
      </testcase>
    </testsuite>
    <testsuite name="padl.serialiser.test.TestDB4OSerialiserArgoUML020" time="0.042">
      <testcase name="testComparator" classname="padl.serialiser.test.TestDB4OSerialiserArgoUML020" time="0.04">
        <error>com.db4o.ext.DatabaseClosedException&#13;
	at com.db4o.internal.ObjectContainerBase.checkClosed(ObjectContainerBase.java:308)&#13;
	at com.db4o.internal.ObjectContainerBase.checkTransaction(ObjectContainerBase.java:336)&#13;
	at com.db4o.internal.ObjectContainerBase.asTopLevelCall(ObjectContainerBase.java:420)&#13;
	at com.db4o.internal.ObjectContainerBase.commit(ObjectContainerBase.java:397)&#13;
	at com.db4o.internal.ExternalObjectContainer.commit(ExternalObjectContainer.java:41)&#13;
	at padl.serialiser.DB4OSerialiser.serialise(DB4OSerialiser.java:131)&#13;
	at padl.serialiser.DB4OSerialiser.serialiseWithAutomaticNaming(DB4OSerialiser.java:114)&#13;
	at padl.serialiser.test.TestDB4OSerialiserArgoUML020.setUp(TestDB4OSerialiserArgoUML020.java:63)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:140)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:130)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
&#13;
</error>
      </testcase>
      <testcase name="testNames" classname="padl.serialiser.test.TestDB4OSerialiserArgoUML020" time="0.001">
        <error>java.lang.NullPointerException: Cannot invoke "padl.kernel.IAbstractLevelModel.getDisplayName()" because "padl.serialiser.test.TestDB4OSerialiserArgoUML020.SerialisedAbstractLevelModel" is null&#13;
	at padl.serialiser.test.TestDB4OSerialiserArgoUML020.testNames(TestDB4OSerialiserArgoUML020.java:91)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)&#13;
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:177)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:142)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:130)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
&#13;
</error>
      </testcase>
    </testsuite>
  </testsuite>
</testrun>
