<?xml version="1.0" encoding="UTF-8"?><testrun name="Rerun padl.serialiser.test.TestDB4OSerialiserSanity.testEntities" project="All Ptidej Tests" tests="1" started="1" failures="0" errors="1" ignored="0">
  <testcase name="testEntities" classname="padl.serialiser.test.TestDB4OSerialiserSanity" time="1.447">
    <error>com.db4o.ext.DatabaseClosedException&#13;
	at com.db4o.internal.ObjectContainerBase.checkClosed(ObjectContainerBase.java:308)&#13;
	at com.db4o.internal.ObjectContainerBase.checkTransaction(ObjectContainerBase.java:336)&#13;
	at com.db4o.internal.ObjectContainerBase.asTopLevelCall(ObjectContainerBase.java:420)&#13;
	at com.db4o.internal.ObjectContainerBase.commit(ObjectContainerBase.java:397)&#13;
	at com.db4o.internal.ExternalObjectContainer.commit(ExternalObjectContainer.java:41)&#13;
	at padl.serialiser.DB4OSerialiser.serialise(DB4OSerialiser.java:131)&#13;
	at padl.serialiser.DB4OSerialiser.serialiseWithAutomaticNaming(DB4OSerialiser.java:114)&#13;
	at padl.serialiser.test.TestDB4OSerialiserSanity.setUp(TestDB4OSerialiserSanity.java:34)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:140)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:130)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:241)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:236)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)&#13;
&#13;
</error>
  </testcase>
</testrun>
